### ISSUE TITLE
模板问题

### ISSUE THREAD

**Issue by Felix230** [xfdywy/bjtu-thesis-templete#1]
大神，我下载了模板，然后用texstudio编译，也把编译器调整到xelatex，但是编译不通过，提示无法启动xelatex，这是为啥？我又用网上随便的一个代码敲了一下，然后是能运行的，不知道是模板哪里的问题？

**Comment by xfdywy** [comment]
你是在学校论坛上给我留言的那位吗？你在论坛上给我发的那几张图我不知道为啥看不见。你在这里发一下吧。你截图发下编译报错的错误信息。然后发下你的texlive版本号。

**Comment by Felix230** [comment]
你好，辛苦您了，我还没发现论坛出现这样的问题，这是我打开后出现的一些标红的地方

然后编译的话，就是这个样子的，之前还有错误提示，现在也不弹了

我的版本是在清华官网下载的，应该是2020的最新版本。


真的是不好意思挺麻烦您的，您先看下吧，我不着急，不行就还是用word去写了



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yue Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月29日(星期五) 晚上8:12
收件人:&nbsp;"xfdywy/bjtu-thesis-templete"<bjtu-thesis-templete@noreply.github.com&gt;;
抄送:&nbsp;"Felix"<1561978501@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xfdywy/bjtu-thesis-templete] 模板问题 (#1)





 
你是在学校论坛上给我留言的那位吗？你在论坛上给我发的那几张图我不知道为啥看不见。你在这里发一下吧。你截图发下编译报错的错误信息。然后发下你的texlive版本号。

**Comment by xfdywy** [comment]
还是没看见图片。估计你是回邮件了吧。或许你需要来github上回复我才能看见。论坛上好像有一个人跟你问一样的问题。。。。。我没看到具体的出问题的图片。。所以我也不知道是啥问题。我自己从github上clone一份下来，直接编译没问题。所以可能需要你提供一下截图啥的我才能确定。

**Comment by Felix230** [comment]
![e2b645c8fd92fd771a6e19cf571607c4](https://user-images.githubusercontent.com/42661993/83323228-dd987280-a28f-11ea-9ecc-c02921616e09.png)
![1e06ff9ea4ef6f03d18a099d1469eb36](https://user-images.githubusercontent.com/42661993/83323229-dec99f80-a28f-11ea-9e70-79898ea85d92.png)
现在能看到了吗？

**Comment by xfdywy** [comment]
你搞错了。。你编译那个demo.tex， 这个cls是模版文件。放在demo.tex同目录下，负责定义论文的模版的。你再试试，打开demo.tex，编译一下试试

**Comment by Felix230** [comment]
哇，太蠢了，竟然是文件打开错了，直接编译demo就没有问题了，多谢大神~

**Comment by xfdywy** [comment]
嗯啊。没问题就好。我搞了一个小demo，你可以研究研究，不同章节放在了不同文件里面，都在demo.tex里面引用进来就好，这样大论文写起来比较容易管理，不会乱，不会想找一个东西半天找不到。如果有啥与学校要求不符的格式，你可以告诉我。不过应该没有大问题，我的博士论文前两天送审通过了，哈哈。所以应该是符合要求的。
