### ISSUE TITLE
[Question] 请问可以直接在Overleaf上编译吗

### ISSUE THREAD

**Issue by EricWangCN** [xfdywy/bjtu-thesis-templete#10]
我尝试直接将这个Project传到overleaf上，无论怎么编译好像都没中文。

**Comment by xfdywy** [comment]
我没试过。但是应该没问题吧。你要把编译器选成xelatex，不可以用pdflatex。你可以试试

**Comment by EricWangCN** [comment]
非常感谢，好像又可以了，同一套config前两天还不行来着，非常感谢~
