### ISSUE TITLE
部分章节的字号大小

### ISSUE THREAD

**Issue by lzhtan** [xfdywy/bjtu-thesis-templete#3]
索引、作者简历及攻读硕士/博士学位期间取得的研究成果、独创性声明、学位论文数据集的字体是不是5号？感觉比学校word模版的字号大？这个字号如何修改啊？

**Comment by xfdywy** [comment]
我有个简单的办法，这几页反正是在最后，填个表就行，你就用word做，做好了，生成一个pdf，然后在latex里面引用上最后这些的pdf。

操作方法是，如果你的pdf文件叫做infomation.pdf,然后放在chapter文件夹里面，那么你在主文件（比如我这里叫demo.tex）里面，对应的位置写下面这个语句。

\includepdf[page=-]{chapters/infomation.pdf}
