### ISSUE TITLE
日期和空白页页码

### ISSUE THREAD

**Issue by gengu2** [xfdywy/bjtu-thesis-templete#6]
建议在demo.tex提供修改日期的代码。另外空白页面应该需要页眉和页码

**Comment by xfdywy** [comment]
日期可以在BJTU-thesis.cls 文件的182行附近做修改，你打开进去应该就能看明白，应该写成可变的参数，不过懒得搞了，就写死在模版里面了。 

至于空白页是否需要页眉页码， 我的模版以及我最后提交的论文确实空白页是没有的。不知道有什么规范可以参考吗？latex默认的book类型，空白页应该就是没有页眉页码的？

**Comment by gengu2** [comment]
是的，日期我在那里改了。另外建议在demo.tex加句学硕的注释 % \documentclass[AcMaster]{BJTU-thesis}，目前只有博士的
因为空白页没页码，但是其下一页的页码还是把上一页空白页算页码了，就是页码没有连贯显示。比如上一页是21页（有页码），空白页是22页（没页码），在下一页是23页了（有页码）

**Comment by xfdywy** [comment]
硕士那个我应该加上。主要是我没测试过硕士的模版和学校发的是不是一样。

至于你说的页码那个，本来就应该是这样吧，你找本书看看:)

**Comment by gengu2** [comment]
目前看基本是一样的，我之前用学校单页模板写完了，发现换学校双页模板编译不通过才找到大佬的模板。学校那个双页模板应该是用texlive差一些CJK相关包。

好的，页码没问题就行，之前是觉得有点反直觉，结果是看书太少 -.-

**Comment by xfdywy** [comment]
嗯啊~   有问题可以继续反馈。我自己用的这个模版20年毕业的。所以应该没啥大问题，如果学校没有改模版的话   ~
