### ISSUE TITLE
直接编译，报这样的错怎么办，不太会用

### ISSUE THREAD

**Issue by kyleflower** [xfdywy/bjtu-thesis-templete#7]
c:\documents\bjtu-thesis-templete-master>docker run -i --rm -w /data -v "c:\documents\bjtu-thesis-templete-master:/data" tianon/latex xelatex  -synctex=1 -interaction=nonstopmode  "-synctex=1" "-interaction=nonstopmode" "-file-line-error" "demo" 
'docker' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

**Comment by xfdywy** [comment]
不用执行docker下面的命令，那个是我自己试着玩的。

你安装好texlive，然后安装一个写latex的软件，比如texstudio，然后选择tex文件，比如demo.tex ，然后点编译按钮就好了。

**Comment by xfdywy** [comment]
你可以参考这个。 https://blog.wyue.site/2019/03/01/1/
