### ISSUE TITLE
封面信息页至目录页中间页码数不正确（由于设置了空白页）

### ISSUE THREAD

**Issue by C-Dragon8** [xfdywy/bjtu-thesis-templete#8]
您好！如题目所述，在封面信息页至目录页中间，由于设置了空白页，导致页码数显示不正确。（页码显示为i，iii，v，......）

在目录页处所标记的页码数是正确的，期待版主解决此问题，十分感谢！

**Comment by xfdywy** [comment]
能麻烦你提供一下截图吗。不是很明白问题在哪里。

**Comment by C-Dragon8** [comment]
您在2021年1月3日更新了奇偶页设置为不同的页边距，在BJTU-thesis.cls文件中启用了twoside双面排版，但是这样的话，封面信息页至目录页之间，由于双面排版，按照您demo.pdf里面，这些罗马数字排序，就是i，iii，v，......

不太确定latex启用双页排版是不是就意味着那些空白页也要纳入页码计算范围，按我的理解是空白页可以不再标记页码也不纳入页码计算范围了。如果我理解错了，希望您指正，谢谢您！

![2022-03-09_153708](https://user-images.githubusercontent.com/49544089/157395223-86b8c80f-8edd-486e-86f3-88c208170409.png)

**Comment by xfdywy** [comment]
我感觉空白页应该要算页码的。首先你可以翻一翻你手边的书，应该空白页都算页码的。其次知网上应该可以搜到交大的博士毕业论文，你可以再确认下。

这个是latex的默认排版逻辑，应该是对的吧。而且你填充上内容之后，可能都没这些空白页了，所以从逻辑上来看，算页码也更自然。

**Comment by C-Dragon8** [comment]
嗯嗯好的，谢谢您的回复，我就接受这样的逻辑进行编辑。

多谢您提供模板！正是结合了您的模板，我修改了学校官网给的模板，开启了双面排版。

**Comment by xfdywy** [comment]
嗯啊。能帮上忙就好。有问题可以再提issue

**Comment by C-Dragon8** [comment]
好的谢谢！
